menu:
  page:
    Home: .
    Search: categories/
    Life: about/

sidePic: https://p.ipic.vip/b2t3my.jpg
avatar: https://media.licdn.com/dms/image/v2/D4E03AQG65iFp_C-z3w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1718586178725?e=1744848000&v=beta&t=2bNr8i1wRwC_YqoDZ1Hu5RNWnunIzXe0nkUE3Ttz_xo

excerpt_link: 继续阅读
excerpt: 200

social:
  github: efuente2
  juejin: 201965868418951
  rss: false

# 评论使用 LeanCloud + Valine
# https://www.leancloud.cn/
leancloud:
  appId: XPJzs0FfufkFfuBjbJraqhbo-gzGzoHsz
  appKey: QoS0zL4Y2xTDviitGOPkvCGv
  sdk: https://cdn.jsdelivr.net/npm/leancloud-storage@4.13.2/dist/av.min.js

# https://valine.js.org/
valine:
  sdk: https://unpkg.com/valine@1.5.2/dist/Valine.min.js
  placeholder: 我来说两句
